// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kertaskerja Dev Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "description": "Mengambil audit event berdasarkan filter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "Get Audit Events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama service",
                        "name": "service_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Id Project",
                        "name": "project_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tipe event",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Action: CREATE, UPDATE, DELETE",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tipe entity",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID entity",
                        "name": "entity_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID actor",
                        "name": "actor_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Username actor",
                        "name": "actor_username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Request ID",
                        "name": "request_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Waktu mulai",
                        "name": "occurred_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "description": "Waktu akhir",
                        "name": "occurred_to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Nomor halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Jumlah data",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil audit events",
                        "schema": {
                            "$ref": "#/definitions/web.Response-array_web_AuditEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Menyimpan event audit trail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "Create Audit Event",
                "parameters": [
                    {
                        "description": "Audit Event",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Berhasil membuat audit event",
                        "schema": {
                            "$ref": "#/definitions/web.Response-web_AuditEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "checking if this service is accessible",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.Response-web_HealthcheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.AuditEventResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "UPDATE"
                },
                "actor_id": {
                    "type": "string",
                    "example": "user-002"
                },
                "actor_username": {
                    "type": "string",
                    "example": "operator.opd"
                },
                "after": {
                    "type": "object"
                },
                "before": {
                    "type": "object"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-09-17T08:00:01+07:00"
                },
                "entity_id": {
                    "type": "string",
                    "example": "rk-2026-0001"
                },
                "entity_type": {
                    "type": "string",
                    "example": "rencana_kinerja"
                },
                "event_type": {
                    "type": "string",
                    "example": "DATA_CHANGED"
                },
                "id": {
                    "type": "string",
                    "example": "8f4a2c1e-7b9d-4e62-a3f1-91d8c5b2e704"
                },
                "metadata": {
                    "type": "object"
                },
                "occurred_at": {
                    "type": "string",
                    "example": "2026-09-17T08:00:00+07:00"
                },
                "project_id": {
                    "type": "string",
                    "example": "mahulu"
                },
                "request_id": {
                    "type": "string",
                    "example": "req-004"
                },
                "service_name": {
                    "type": "string",
                    "example": "perencanaan-service"
                },
                "session_id": {
                    "type": "string",
                    "example": "sess-004"
                }
            }
        },
        "web.CreateEventRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "actor_id": {
                    "type": "string"
                },
                "actor_username": {
                    "type": "string"
                },
                "after": {},
                "before": {},
                "entity_id": {
                    "type": "string"
                },
                "entity_type": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "occurred_at": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "web.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "system_info": {
                    "$ref": "#/definitions/web.HealthcheckSystemInfo"
                }
            }
        },
        "web.HealthcheckSystemInfo": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "web.Response-array_web_AuditEventResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.AuditEventResponse"
                    }
                }
            }
        },
        "web.Response-web_AuditEventResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.AuditEventResponse"
                }
            }
        },
        "web.Response-web_HealthcheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/web.HealthcheckResponse"
                }
            }
        },
        "web.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "tahun": "required"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Penetapan Service",
	Description:      "Service snapshot penetapan tujuan, sasaran, renja, rekin untuk pemda, opd, dan individu",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
